/*
  @author: tossbrink
*/
drop user ORDS_PUBLIC_USER1 cascade
/
CREATE USER "ORDS_PUBLIC_USER1" IDENTIFIED BY "{password}"
DEFAULT TABLESPACE "USERS" QUOTA UNLIMITED ON "USERS"
TEMPORARY TABLESPACE "TEMP"
/
GRANT "CONNECT", "RESOURCE" TO "ORDS_PUBLIC_USER1"
/
BEGIN
    ORDS_ADMIN.PROVISION_RUNTIME_ROLE(
        p_user => 'ORDS_PUBLIC_USER1',
        p_proxy_enabled_schemas => TRUE);
END;
/
commit
/
drop user TOSSBRINK cascade
/
CREATE USER "TOSSBRINK" IDENTIFIED BY "{password}"
DEFAULT TABLESPACE "USERS" QUOTA UNLIMITED ON "USERS"
TEMPORARY TABLESPACE "TEMP"
/
GRANT "CONNECT", "RESOURCE" TO "TOSSBRINK"
/
GRANT CREATE SESSION TO "TOSSBRINK"
/
GRANT UNLIMITED TABLESPACE TO "TOSSBRINK"
/
GRANT CREATE TABLE,CREATE VIEW,CREATE SEQUENCE,CREATE PROCEDURE,CREATE TYPE,CREATE SYNONYM TO "TOSSBRINK"
/
GRANT "ORDS_RUNTIME_ROLE" TO "TOSSBRINK" WITH ADMIN OPTION
/
GRANT "ORDS_ADMINISTRATOR_ROLE" TO "TOSSBRINK" WITH ADMIN OPTION
/
BEGIN
   ORDS_ADMIN.ENABLE_SCHEMA(
     p_enabled => TRUE,
     p_schema => 'TOSSBRINK',
     p_url_mapping_type => 'BASE_PATH',
     p_url_mapping_pattern => 'tossbrink',
     p_auto_rest_auth => TRUE
   );
   COMMIT;
END;
/
--Enable :- ORDS_ADMINISTRATOR & ORDS_RUNTIME_ROLE  for TOSSBRINK using ADMIN
exit
